[project]
name = "streamlitbp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=6.0.0",
    "pandas>=2.3.3",
    "streamlit>=1.53.0",
]
